services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: axisor-postgres-prod
    environment:
      POSTGRES_DB: axisor
      POSTGRES_USER: axisor
      POSTGRES_PASSWORD: axisor_dev_password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - axisor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axisor -d axisor"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7
    container_name: axisor-redis-prod
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - axisor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: axisor-backend-prod
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://axisor:axisor_dev_password@postgres:5432/axisor?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 3010
    ports:
      - "23000:3010"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3010/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: axisor-frontend-prod
    environment:
      VITE_API_URL: https://api.defisats.site
    ports:
      - "23001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3001', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Workers (opcionais para desenvolvimento)
  margin-monitor:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: axisor-margin-monitor-prod
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://axisor:axisor_dev_password@postgres:5432/axisor?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run worker:margin-monitor
    profiles:
      - workers

  automation-executor:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: axisor-automation-executor-prod
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://axisor:axisor_dev_password@postgres:5432/axisor?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run worker:automation-executor
    profiles:
      - workers

  notification-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: axisor-notification-worker-prod
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://axisor:axisor_dev_password@postgres:5432/axisor?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run worker:notification
    profiles:
      - workers

  payment-validator:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: axisor-payment-validator-prod
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://axisor:axisor_dev_password@postgres:5432/axisor?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - axisor-network
    command: npm run worker:payment-validator
    profiles:
      - workers

volumes:
  postgres_data:
  redis_data:

networks:
  axisor-network:
    driver: bridge
