global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Backend API
  - job_name: 'axisor-backend'
    static_configs:
      - targets: ['backend:3010']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Frontend Application
  - job_name: 'axisor-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx Web Server
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # Workers
  - job_name: 'margin-monitor'
    static_configs:
      - targets: ['margin-monitor:3010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'automation-executor'
    static_configs:
      - targets: ['automation-executor:3010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notification-worker'
    static_configs:
      - targets: ['notification-worker:3010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'payment-validator'
    static_configs:
      - targets: ['payment-validator:3010']
    metrics_path: '/metrics'
    scrape_interval: 30s

