#!/bin/bash

# Script para obter Bitcoin testnet via faucets on-chain
# Endereço: tb1q3mu9j99d06edl8t7pxxgmwurrsgnwnqwemfhjj

echo "🚀 Bitcoin Testnet Funding via On-Chain Faucets"
echo "==============================================="
echo ""
echo "📍 Endereço Bitcoin Testnet:"
echo "tb1q3mu9j99d06edl8t7pxxgmwurrsgnwnqwemfhjj"
echo ""
echo "📋 Faucets Bitcoin Testnet Recomendados:"
echo "======================================="
echo ""
echo "1. 🌐 Mempool.space Testnet Faucet"
echo "   URL: https://testnet-faucet.mempool.co/"
echo "   Valor: ~0.001 BTC testnet"
echo "   Instruções:"
echo "   - Cole o endereço acima"
echo "   - Clique em 'Send testnet bitcoin'"
echo "   - Aguarde confirmação"
echo ""
echo "2. 🌐 Testnet Faucet Bitcoin"
echo "   URL: https://testnet.help/en/bitcoincoinfaucet/testnet/"
echo "   Valor: ~0.001 BTC testnet"
echo "   Instruções:"
echo "   - Cole o endereço acima"
echo "   - Clique em 'Get Testnet Bitcoin'"
echo "   - Aguarde confirmação"
echo ""
echo "3. 🌐 Coinfaucet.eu"
echo "   URL: https://coinfaucet.eu/en/btc-testnet/"
echo "   Valor: ~0.001 BTC testnet"
echo "   Instruções:"
echo "   - Cole o endereço acima"
echo "   - Clique em 'Get Bitcoins'"
echo "   - Aguarde confirmação"
echo ""

echo "⏳ Monitor de Saldo On-Chain:"
echo "============================"
echo ""
echo "Para verificar se recebeu os sats:"
echo "./scripts/check-onchain-balance.sh"
echo ""

echo "🔧 Após receber Bitcoin testnet:"
echo "==============================="
echo ""
echo "1. Verificar saldo on-chain"
echo "2. Criar canal Lightning (opcional)"
echo "3. Usar os sats para testar a aplicação"
echo ""

echo "📊 Saldo atual on-chain:"
docker exec axisor-lnd-testnet lncli --network=testnet --tlscertpath=/root/.lnd/tls.cert --macaroonpath=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon walletbalance
echo ""

echo "✅ Pronto para usar os faucets!"
echo "Escolha um dos faucets acima e use o endereço fornecido."
