name: Documentation Build and Deploy

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'docs/**'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
    
    - name: Validate Markdown
      run: |
        markdownlint docs/**/*.md --ignore node_modules
        echo "✅ Markdown validation completed"
    
    - name: Check YAML metadata
      run: |
        find docs -name "*.md" -exec grep -L "^---" {} \; | head -10
        echo "✅ YAML metadata check completed"
    
    - name: Validate links
      run: |
        echo "Checking for broken internal links..."
        # Basic link validation - can be enhanced with linkchecker
        find docs -name "*.md" -exec grep -o "\[.*\](\./[^)]*)" {} \; | head -10
        echo "✅ Link validation completed"

  build-docs:
    needs: validate-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Docusaurus
      run: |
        npm install -g @docusaurus/init
        npm install @docusaurus/core @docusaurus/preset-classic
    
    - name: Create Docusaurus config
      run: |
        cat > docusaurus.config.js << 'EOF'
        module.exports = {
          title: 'Axisor Documentation',
          tagline: 'Complete Trading Automation Platform',
          url: 'https://axisor-docs.github.io',
          baseUrl: '/',
          onBrokenLinks: 'warn',
          onBrokenMarkdownLinks: 'warn',
          favicon: 'img/favicon.ico',
          organizationName: 'axisor',
          projectName: 'axisor-docs',
          themeConfig: {
            navbar: {
              title: 'Axisor Docs',
              logo: {
                alt: 'Axisor Logo',
                src: 'img/logo.svg',
              },
              items: [
                {
                  to: 'docs/',
                  activeBasePath: 'docs',
                  label: 'Docs',
                  position: 'left',
                },
                {
                  href: 'https://github.com/axisor/axisor',
                  label: 'GitHub',
                  position: 'right',
                },
              ],
            },
            footer: {
              style: 'dark',
              links: [
                {
                  title: 'Docs',
                  items: [
                    {
                      label: 'Architecture',
                      to: 'docs/architecture/',
                    },
                    {
                      label: 'API Reference',
                      to: 'docs/integrations/',
                    },
                  ],
                },
                {
                  title: 'Community',
                  items: [
                    {
                      label: 'GitHub',
                      href: 'https://github.com/axisor/axisor',
                    },
                  ],
                },
              ],
              copyright: `Copyright © ${new Date().getFullYear()} Axisor Platform. Built with Docusaurus.`,
            },
          },
          presets: [
            [
              '@docusaurus/preset-classic',
              {
                docs: {
                  sidebarPath: require.resolve('./docs/_sidebar.md'),
                  editUrl: 'https://github.com/axisor/axisor/edit/main/',
                },
                theme: {
                  customCss: require.resolve('./src/css/custom.css'),
                },
              },
            ],
          ],
        };
        EOF
    
    - name: Build documentation
      run: |
        mkdir -p src/css
        echo '/* Custom CSS for Axisor Docs */' > src/css/custom.css
        npx docusaurus build
        echo "✅ Documentation build completed"
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: docs.axisor.com
